/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IFaSolidBoxOpen: typeof import('~icons/fa-solid/box-open')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IPhAnchorSimpleThin: typeof import('~icons/ph/anchor-simple-thin')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
